# Generated by Django 2.1.3 on 2018-12-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PieceType',
            fields=[
                ('type_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('roleName', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='permissions', serialize=False, to='DjanGIUnchained.Role')),
                ('screen', models.CharField(max_length=50)),
                ('access', models.BooleanField()),
                ('modification', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roleName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='DjanGIUnchained.Role'),
        ),
        migrations.AddField(
            model_name='pieces',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='DjanGIUnchained.PieceType'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('roleName', 'screen')},
        ),
    ]
