# Generated by Django 2.1.3 on 2018-12-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjanGIUnchained', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='permission_id',
        ),
        migrations.AddField(
            model_name='permission',
            name='id',
            field=models.AutoField(auto_created=True, default=int, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
