# Generated by Django 2.1.3 on 2018-12-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjanGIUnchained', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('screen', 'roleName')},
        ),
    ]
